version: '3.8'
services:

  # frontend:
  #   build: ./frontend
  #   container_name: frontend-ReactJs
  #   # command: npm run build && npm run start
  #   command: npm run start
  #   restart: unless-stopped
  #   volumes:
  #     - './frontend:/app'
  #   ports:
  #     - "3070:3070"
  #   environment:
  #     - PORT=3000
  #   stdin_open: true
  #   tty: true
  #   # depends_on:
  #   #   - backend

  # backend:
  #   build: ./backend
  #   container_name: backend-NestJs3
  #   command: npm run start:dev
  #   restart: always
  #   volumes:
  #     - './backend:/app'
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo
  #     - postgres11
  #   expose:
  #     - "5433"
  #   stdin_open: true
  #   tty: true


  postgres11:
    hostname: postgres_db
    image: postgres:11
    container_name: postgres11
    restart: unless-stopped
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
